currency: "EUR"
market: "ES"

routes:
  - id: "ruta1_bcn_to_sfo"
    name: "Barcelona -> San Francisco"
    origin: "Barcelona"
    destination: "SFO"
    date_range:
      start: "2027-05-25"
      end: "2027-05-25"
    max_stops: 1
    max_layover_minutes: 210
    top_n: 5
